#!/usr/bin/env bash
# Agent Zero + Claude Code CLI setup script for EC2
# Installs Agent Zero, configures knowledge base, and creates systemd service
set -euo pipefail

AGENT_ZERO_DIR="$HOME/agent-zero"
POLYMARKET_DIR="$HOME/polymarket-agent"
POLYMARKET_ENV="$POLYMARKET_DIR/.env"

echo "=== Agent Zero + Claude Code CLI Setup ==="

# ─── Step 1: Clone Agent Zero ───
if [ -d "$AGENT_ZERO_DIR" ]; then
    echo "[1/8] Agent Zero directory exists, pulling latest..."
    cd "$AGENT_ZERO_DIR" && git pull origin main
else
    echo "[1/8] Cloning Agent Zero..."
    git clone https://github.com/frdel/agent-zero.git "$AGENT_ZERO_DIR"
fi

# ─── Step 2: Create venv and install deps ───
echo "[2/8] Setting up Python environment..."
cd "$AGENT_ZERO_DIR"
python3 -m venv venv
source venv/bin/activate
pip install --upgrade pip setuptools wheel -q
pip install -r requirements.txt -q
deactivate

# ─── Step 3: Install Claude Code CLI ───
echo "[3/8] Installing Claude Code CLI..."
if command -v claude &>/dev/null; then
    echo "  Claude CLI already installed: $(claude --version 2>/dev/null || echo 'unknown')"
else
    sudo npm install -g @anthropic-ai/claude-code
    echo "  Claude CLI installed"
fi

# ─── Step 4: Configure Agent Zero .env ───
echo "[4/8] Configuring Agent Zero environment..."

# Extract API keys from polymarket .env
get_env_val() {
    grep "^$1=" "$POLYMARKET_ENV" 2>/dev/null | cut -d= -f2- | tr -d '"' || echo ""
}

ANTHROPIC_KEY=$(get_env_val "ANTHROPIC_API_KEY")
OPENAI_KEY=$(get_env_val "OPENAI_API_KEY")
GOOGLE_KEY=$(get_env_val "GOOGLE_API_KEY")
OPENROUTER_KEY=$(get_env_val "OPENROUTER_API_KEY")

# Agent Zero reads settings from usr/settings.json AND A0_SET_* env vars in .env
# Write BOTH to ensure config is picked up regardless of load order

# --- Write .env with A0_SET_ prefixed variables (env var overrides) ---
cat > "$AGENT_ZERO_DIR/.env" << ENVEOF
# Agent Zero Configuration — Auto-generated by setup-agent-zero.sh
# Agent Zero reads env vars prefixed with A0_SET_ to override settings.json defaults

# ─── Chat Model: Haiku 4.5 (cheap dispatcher — real work delegated to Claude Code) ───
A0_SET_chat_model_provider=anthropic
A0_SET_chat_model_name=claude-haiku-4-5-20251001

# ─── Utility Model: Haiku 4.5 (summarization, formatting, simple tasks) ───
A0_SET_util_model_provider=anthropic
A0_SET_util_model_name=claude-haiku-4-5-20251001

# ─── Embedding Model: OpenAI (cheapest, best quality) ───
A0_SET_embed_model_provider=openai
A0_SET_embed_model_name=text-embedding-3-small

# ─── API Keys ───
API_KEY_ANTHROPIC=${ANTHROPIC_KEY}
API_KEY_OPENAI=${OPENAI_KEY}
API_KEY_GOOGLE=${GOOGLE_KEY}
API_KEY_OPENROUTER=${OPENROUTER_KEY}

# ─── Features ───
A0_SET_browser_enabled=true
ENVEOF

# --- Also write usr/settings.json (primary config file) ---
mkdir -p "$AGENT_ZERO_DIR/usr"
python3 -c "
import json, os

settings_file = os.path.join('$AGENT_ZERO_DIR', 'usr', 'settings.json')

# Load existing settings if any
settings = {}
if os.path.exists(settings_file):
    with open(settings_file) as f:
        settings = json.load(f)

# Override model settings
settings.update({
    'chat_model_provider': 'anthropic',
    'chat_model_name': 'claude-haiku-4-5-20251001',
    'util_model_provider': 'anthropic',
    'util_model_name': 'claude-haiku-4-5-20251001',
    'embed_model_provider': 'openai',
    'embed_model_name': 'text-embedding-3-small',
})

with open(settings_file, 'w') as f:
    json.dump(settings, f, indent=2)
print(f'  Settings written to {settings_file}')
"
echo "  .env + settings.json configured (Haiku 4.5 chat + utility, Claude Code for heavy lifting)"

# ─── Step 5: Create knowledge base files ───
echo "[5/8] Creating knowledge base..."
mkdir -p "$AGENT_ZERO_DIR/knowledge/custom/main"

cat > "$AGENT_ZERO_DIR/knowledge/custom/main/mission.md" << 'MISSION'
# MISSION: Polymarket Paper Trading Challenge

## Objective
Grow $100 paper trading bankroll to $1,000 on Polymarket prediction markets.

## Primary Goal
Focus on WIN RATE — make more correct predictions than wrong ones.

## How You Work
1. The trading bot scans markets every hour automatically
2. It stores promising trades as "pending" for your approval
3. Check pending trades: curl -H "Authorization: Bearer $(cat ~/.polymarket-token)" http://localhost:8000/api/trades/pending
4. Present opportunities to the user with simple summaries
5. Wait for user approval before executing trades
6. Monitor open positions, alert on stop-losses at -30%
7. Learn from every trade — log outcomes and lessons in your memory

## Rules
- NEVER switch to live trading mode
- ALWAYS ask user before executing a trade
- ALWAYS explain in simple terms (user is not a developer)
- Log every trade outcome in your memory for learning
MISSION

cat > "$AGENT_ZERO_DIR/knowledge/custom/main/codebase.md" << 'CODEBASE'
# Polymarket Trading Agent — Codebase Reference

## Architecture
- FastAPI backend on port 8000, React dashboard
- 5 autonomous background loops: scan, reconciliation, resolution, arbitrage, price update
- Paper trading with simulated fills via PaperBroker
- SQLite database at ~/polymarket-agent/trading.db

## Key API Endpoints
- GET /health — Bot health status (no auth needed)
- POST /auth/token — Get a JWT token (paper mode, no credentials needed)
- GET /api/trades/pending — List trades awaiting approval (auth required)
- POST /api/trades/approve/{id} — Approve a pending trade (operator auth)
- POST /api/trades/reject/{id} — Reject a pending trade (operator auth)
- GET /api/portfolio/summary — Portfolio overview (auth required)
- GET /api/controls/state — Trading state (paused, mode, breakers)
- POST /api/controls/trading — Pause/resume trading (operator auth)

## Key Directories
- Trading bot code: ~/polymarket-agent/src/
- Bot logs: ~/polymarket-agent/logs/
- Database: ~/polymarket-agent/trading.db
- Bot config: ~/polymarket-agent/.env (READ ONLY)

## Useful Commands
- Check bot: sudo systemctl status polymarket-agent
- Restart bot: sudo systemctl restart polymarket-agent
- View errors: tail -50 ~/polymarket-agent/logs/agent-error.log
- Run tests: cd ~/polymarket-agent && source venv/bin/activate && pytest
- Get auth token: curl -X POST http://localhost:8000/auth/token | jq -r .access_token
- Git pull: cd ~/polymarket-agent && git pull origin main
- Git push: cd ~/polymarket-agent && git push origin main
- Git status: cd ~/polymarket-agent && git status

## Claude Code CLI
For coding tasks: claude -p "your instruction here"
Working directory: ~/polymarket-agent
GitHub: Auto-commits and pushes after every coding session

## LLM Cost Tiers
- Chat (Opus 4.6): Complex reasoning, market analysis — paid
- Utility (OpenRouter free): Simple tasks, formatting — FREE
- Embeddings (OpenAI): Memory search — cheapest
CODEBASE

cat > "$AGENT_ZERO_DIR/knowledge/custom/main/trading-strategy.md" << 'STRATEGY'
# Trading Strategy Knowledge

## How Edge Is Calculated
1. AI estimates the TRUE probability of an event (e.g., 70%)
2. Compare to the market price (e.g., 55 cents = 55% implied probability)
3. Edge = True probability - Market price - Fees
4. If edge > 3%, it's a trade opportunity

## Kelly Criterion (Position Sizing)
- Kelly fraction = (edge / odds) — tells you what % of bankroll to bet
- We use HALF Kelly (0.5x) — aggressive but not reckless
- Max 30% of bankroll on any single position
- Max 10 open positions at a time

## Risk Management
- Stop-loss at -30%: auto-sell if position drops 30% from entry
- Circuit breakers: auto-pause if daily loss exceeds threshold
- Correlation limits: don't overload on similar markets

## What Makes a Good Trade
- Clear, verifiable question with known resolution date
- Sufficient liquidity (>$500) so we can enter/exit
- Market price significantly different from our estimate (>3% edge)
- High confidence in our probability estimate
- NOT too close to resolution (prices become unpredictable near expiry)

## Common Pitfalls
- Overconfidence in AI estimates (they're often wrong)
- Trading illiquid markets (can't exit when needed)
- Correlated positions (multiple bets on same underlying event)
- Ignoring fees (2% taker fee eats into small edges)
STRATEGY

# ─── Step 5b: Deploy custom agent profile ───
echo "  Deploying custom agent profile..."
PROFILE_SRC="$POLYMARKET_DIR/agent-zero-profile"
PROFILE_DST="$AGENT_ZERO_DIR/agents/polymarket-trader"
PROMPTS_DIR="$AGENT_ZERO_DIR/prompts"
TOOLS_DIR="$AGENT_ZERO_DIR/python/tools"
if [ -d "$PROFILE_SRC" ]; then
    # Deploy to agent profile directory
    mkdir -p "$PROFILE_DST"
    cp "$PROFILE_SRC"/*.md "$PROFILE_DST/"
    echo "  Profile deployed to $PROFILE_DST"

    # ALSO deploy to prompts/ directory (belt and suspenders — works even without profile selection)
    echo "  Also deploying to prompts/ directory for default profile..."
    cp -f "$PROFILE_SRC"/agent.system.main.behaviour.md "$PROMPTS_DIR/"
    cp -f "$PROFILE_SRC"/agent.system.main.environment.md "$PROMPTS_DIR/"
    cp -f "$PROFILE_SRC"/agent.system.main.role.md "$PROMPTS_DIR/"
    cp -f "$PROFILE_SRC"/agent.system.tool.claude_code.md "$PROMPTS_DIR/"
    # Preserve original behaviour.md template but append our override
    if grep -q '{{rules}}' "$PROMPTS_DIR/agent.system.behaviour.md" 2>/dev/null; then
        cp -f "$PROFILE_SRC"/agent.system.behaviour.md "$PROMPTS_DIR/"
        echo "  Patched agent.system.behaviour.md with override directive"
    else
        cp -f "$PROFILE_SRC"/agent.system.behaviour.md "$PROMPTS_DIR/"
    fi
    echo "  Prompt files deployed to $PROMPTS_DIR"

    # Deploy Claude Code CLI tool
    if [ -f "$PROFILE_SRC/claude_code_cli.py" ] && [ -d "$TOOLS_DIR" ]; then
        cp -f "$PROFILE_SRC/claude_code_cli.py" "$TOOLS_DIR/"
        echo "  Claude Code CLI tool deployed to $TOOLS_DIR"
    elif [ -f "$PROFILE_SRC/claude_code_cli.py" ]; then
        mkdir -p "$TOOLS_DIR"
        cp -f "$PROFILE_SRC/claude_code_cli.py" "$TOOLS_DIR/"
        echo "  Claude Code CLI tool deployed to $TOOLS_DIR (created dir)"
    fi
else
    echo "  WARNING: Profile source not found at $PROFILE_SRC"
fi

# ─── Step 6: Create Claude Code wrapper ───
echo "[6/8] Creating Claude Code wrapper script..."
cat > "$HOME/claude-trade.sh" << 'WRAPPER'
#!/usr/bin/env bash
# Claude Code wrapper for Agent Zero integration
export ANTHROPIC_API_KEY=$(grep "^ANTHROPIC_API_KEY=" ~/polymarket-agent/.env | cut -d= -f2- | tr -d '"')
cd ~/polymarket-agent
claude -p "$@"
WRAPPER
chmod +x "$HOME/claude-trade.sh"

# ─── Step 7: Generate service token ───
echo "[7/8] Generating API service token..."
TOKEN=$(curl -s -X POST http://localhost:8000/auth/token 2>/dev/null | python3 -c "import sys,json; print(json.load(sys.stdin).get('access_token',''))" 2>/dev/null || echo "")
if [ -n "$TOKEN" ]; then
    echo "$TOKEN" > "$HOME/.polymarket-token"
    chmod 600 "$HOME/.polymarket-token"
    echo "  Token saved to ~/.polymarket-token"
else
    echo "  WARNING: Could not generate token (bot may not be running yet)"
    echo "  Run this after bot starts: curl -s -X POST http://localhost:8000/auth/token | python3 -c \"import sys,json; print(json.load(sys.stdin)['access_token'])\" > ~/.polymarket-token"
fi

# ─── Step 8: Create systemd service ───
echo "[8/8] Creating systemd service..."
sudo tee /etc/systemd/system/agent-zero.service > /dev/null << SERVICEEOF
[Unit]
Description=Agent Zero AI Assistant
After=network.target polymarket-agent.service
Wants=polymarket-agent.service

[Service]
Type=simple
User=$(whoami)
WorkingDirectory=$AGENT_ZERO_DIR
Environment=PATH=$AGENT_ZERO_DIR/venv/bin:/usr/local/bin:/usr/bin:/bin
ExecStart=$AGENT_ZERO_DIR/venv/bin/python run_ui.py
Restart=on-failure
RestartSec=10

[Install]
WantedBy=multi-user.target
SERVICEEOF

sudo systemctl daemon-reload
sudo systemctl enable agent-zero
echo "  Service created (not started yet)"

echo ""
echo "=== Setup Complete ==="
echo "Start Agent Zero:   sudo systemctl start agent-zero"
echo "Web UI:             http://localhost:50001"
echo "Check status:       sudo systemctl status agent-zero"
echo ""
echo "IMPORTANT: If the Polymarket bot wasn't running during setup,"
echo "regenerate the token after starting it:"
echo "  curl -s -X POST http://localhost:8000/auth/token | python3 -c \"import sys,json; print(json.load(sys.stdin)['access_token'])\" > ~/.polymarket-token"
